version: '3.8'

services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      CHROMA_SERVER_BIND: "0.0.0.0"
      CHROMA_SERVER_PORT: "8000"
      ANONYMIZED_TELEMETRY: true
      IS_PERSISTENT: true
    volumes:
      - ./chroma:/chroma/chroma
volumes:
  chromadb_data:
    driver: local